compiler/lib/Dialect/Linalg/Transforms/FuseElementwise.cpp, compiler/test/Dialect/Linalg/linalg-fuse-elementwise-ext-existing.mlir, compiler/test/Dialect/Linalg/linalg-fuse-elementwise-ext.mlir
Before this patch, when applying `-linalg-fuse-elementwise-ext -cse` on 
```
#map = affine_map<(d0, d1) -> (d0, d1)>
func.func @consumer_multi_result_from_producer(%arg0: tensor<2x4xf32>, %arg1: tensor<2x4xf32>) -> (tensor<2x4xf32>, tensor<2x4xf32>, tensor<2x4xf32>) {
%0 = tensor.empty() : tensor<2x4xf32>
%1 = tensor.empty() : tensor<2x4xf32>
%2 = tensor.empty() : tensor<2x4xf32>
%3 = tensor.empty() : tensor<2x4xf32>
%4:3 = linalg.generic {indexing_maps = [#map, #map, #map, #map, #map], iterator_types = ["parallel", "parallel"]} ins(%arg0, %arg1 : tensor<2x4xf32>, tensor<2x4xf32>) outs(%0, %1, %3 : tensor<2x4xf32>, tensor<2x4xf32>, tensor<2x4xf32>) {
^bb0(%in: f32, %in_0: f32, %out: f32, %out_1: f32, %out_2: f32):
%6 = arith.maxf %in, %in_0 : f32
%7 = arith.minf %in, %in_0 : f32
%8 = …
```
=> [Linalg] fix element-fusion for multi-operands from the same producer

compiler/lib/Dialect/mhlo/Transforms/HloFolder.cpp
Fixed a error from Mac env. 
error: non-constant-expression cannot be narrowed from type 'uint64_t' (aka 'unsigned long long') to 'long long' in initializer list [-Wc++11-narrowing]
=> [Compiler/mhlo] changed implicit cast to explicit one due to a Mac clang error

.github/workflows/compiler-and-runtime-build.yml, .github/workflows/e2e_test.yaml, .github/workflows/torch-frontend-ci.yml
I would like to replace pull_request with pull_request_target so that pull requests from forks could work properly. I fix it by adding an environment for deployment. When someone would like to make a pull request from a fork, we would run their code in the environment called github-ci. Maintainers **must** make sure the code is safe to run before approval. Once someone with the access approves the workflow, it will run as usual.
I notice that @zhekunz2 has added a rule to make sure there is only one flow using the same concurrency group. If the workflow gets cancelled accidentally, we could just proceed to the failed action and approve it again to get it started.
The yaml file is not checked into our repo so it doesn't run properly for now, but I test it at …
=> Replace pull_request with pull_request_target to make pull requests from forks work 

compiler/lib/Dialect/mhlo/Util/Util.cpp
With clag 15 you would get
```
error: explicit instantiation of 'mlir::isValidPoolOrPoolGradLayout' must occur in namespace 'mlir'
```
See: https://docwiki.embarcadero.com/RADStudio/Alexandria/en/Explicit_instantiation_of_%27namespace::templated_class%27_must_occur_in_namespace_%27namespace%27_(C%2B%2B)
This PR fixes this error.
=> Fix explicit instantiation of template functions

.github/workflows/compiler-and-runtime-build.yml, .github/workflows/daily_ci.yaml, .github/workflows/e2e_test.yaml, .github/workflows/torch-frontend-ci.yml, scripts/compiler/build_and_lit_test.sh, scripts/compiler/build_and_test_cat.sh, scripts/e2e/build_and_test_e2e.sh, scripts/frontends/torch-frontend/build_and_test.sh, scripts/prepare.sh, scripts/runtime/build_and_test.sh
This pull request:
- move llvm path to scripts/prepare.sh
- add daily ci test
- no longer need deployment in the environment
=> [ci] move llvm_path to prepare.sh, remove environment, add daily ci

compiler/lib/Dialect/mhlo/Transforms/HloAggressiveFusion.cpp, compiler/test/Dialect/Mhlo/transforms/aggressiveFusion.mlir
* leave single reshape on host so it could be lowered to `byre.alias`.
=> [compiler] do not fusion single reshape in aggressive fusion

frontends/tf-frontend/external/patches/tensorflow/fix-bug-of-create-f16-const-for-HoistCwiseBinaryOutO.patch
fix bug of creating f16 constant using float variable in concat canonicalize pattern
=> [tf-frontend] fix bug of creating f16 const in concat canonicalize pattern

frontends/tf-frontend/tf_mlir_ext/pipelines/customized_tf_to_mhlo.cc, frontends/tf-frontend/tf_mlir_ext/pipelines/customized_tf_to_mhlo.h, frontends/tf-frontend/tf_mlir_ext/pipelines/passes.td, frontends/tf-frontend/tf_mlir_ext/tests/mhlo_legalize_tf_ext.mlir, frontends/tf-frontend/tf_mlir_ext/tests/set_assuming_to_be_true.mlir, frontends/tf-frontend/tf_mlir_ext/transforms/BUILD, frontends/tf-frontend/tf_mlir_ext/transforms/mhlo_legalize_tf_ext.cc, frontends/tf-frontend/tf_mlir_ext/transforms/passes.td, frontends/tf-frontend/tf_mlir_ext/transforms/remove_cstr_reshapable.cc, frontends/tf-frontend/tf_mlir_ext/transforms/remove_cstr_reshapable.h, frontends/tf-frontend/tools/tf_frontend_main.cc
add remove cstr_reshapable pass
add remove cstr_broadcastable pass
add BatchMatMulV2 to dot_general pattern
add test case for cstr_reshapable, cstr_broadcastable, BatchMatMulV2
add set-assuming-to-be-true flag
add CreateTFExecutorGraphPruningPass pass
=> [tf-frontend] remove shape.split_at, shape.cstr_broadcastable, mhlo.cstr_reshapable

compiler/dialects/include/byteir/Dialect/Ccl/IR/CclOps.td, compiler/dialects/lib/Dialect/Ccl/IR/CclOps.cpp, compiler/lib/Dialect/Ccl/TransformOps/CclTransformOps.cpp, compiler/lib/Dialect/Linalg/TransformOps/LinalgExtTransformOps.cpp, compiler/lib/Utils/TileUtils.cpp, compiler/test/Dialect/Ccl/ccl_move_down.mlir, compiler/test/Dialect/Ccl/decompose_all_reduce.mlir, compiler/test/Dialect/Ccl/invalid.mlir, compiler/test/Dialect/Ccl/ops.mlir, frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToCcl.cpp, frontends/torch-frontend/torch-frontend/lib/Pipelines/Pipelines.cpp, frontends/torch-frontend/torch-frontend/python/CMakeLists.txt, frontends/torch-frontend/torch-frontend/python/test/test_ccl.py, frontends/torch-frontend/torch-frontend/python/torch_frontend/__init__.py, frontends/torch-frontend/torch-frontend/python/torch_frontend/compile.py, frontends/torch-frontend/torch-frontend/test/Conversion/ConvertTorchToCcl.mlir
1. add `synchronous` attribute to all ccl dialect ops.
2. change `ccl.wait_tensor` to `ccl.wait`, because in future we may do bufferization on ccl dialect.
3. add definition of `ccl.send` and `ccl.recv`.
4. add all_gather and reduce_scatter's lowering to ccl dialect.
5. change filename `torch-frontend/convert_to_mhlo.py` to `torch-frontend/compile.py`.
6. add python test for ccl.
=> [torch-frontend] add more ops for lowering to ccl dialect

compiler/cmake/CMakeLists.txt, compiler/cmake/mhlo.cmake, compiler/include/byteir-c/Dialects.h, compiler/lib/CAPI/Dialects.cpp, compiler/python/ByteIRModules.cpp, compiler/python/CMakeLists.txt, compiler/python/byteir/_mlir_libs/_site_initialize_0.py
1. fix cmake.
2. use stablehlo & chlo's python binding, instead of register them in ByteIRModules.
3. add register_ace_dialect and register_ccl_dialect.
=> [compiler] use stablehlo & chlo's python binding

compiler/lib/Analysis/SideEffect.cpp, compiler/lib/Transforms/SetSpace.cpp, compiler/test/Transforms/setArgSpace.mlir
* allow ViewLikeOp have memory space attribute, and ensure that ViewLikeOp's memory space is same as space attribute.
=> [compiler] fix set-arg-space on ViewLikeOp

compiler/lib/Transforms/SetSpace.cpp, compiler/test/Transforms/setArgSpace.mlir, compiler/test/Transforms/setOpAndArgSpace.mlir
- fix InsertionPoint of `createCopyInputArg`
- support dynamic shape when create a new allocOp(`createCopyInputArg` / `createCopyReturn`/..)
=> [compiler] fix input arg reuse and support dynamic shape

compiler/lib/Transforms/SetSpace.cpp, compiler/test/Transforms/setArgSpace.mlir, compiler/test/Transforms/setOpAndArgSpace.mlir
fix traversal order of arg users  in SetSpace
=> [compiler] fix traversal order of arg users in SetSpace

runtime/lib/backends/cpu/device/llvm/jit.cc
* to support cast from `f64` to `f16` on cpu.
=> [runtime] register __truncdfhf2 in jit

compiler/include/byteir-c/Translation.h, compiler/include/byteir/Target/PTX/ToPTX.h, compiler/lib/CAPI/Translation.cpp, compiler/lib/Target/PTX/TranslateToPTX.cpp, compiler/python/ByteIRModules.cpp, compiler/python/byteir/compile.py
* `MlirModule` is more strict than `MlirOperation`.
=> [compiler] change capi from MlirOperation to MlirModule

compiler/doc/byteir_mhlo_custom_call.md, frontends/onnx-frontend/onnx-frontend/src/Conversion/OFRewriteToCustomCall.cpp, frontends/onnx-frontend/onnx-frontend/src/Conversion/OFRewriteToCustomCall.td, frontends/onnx-frontend/onnx-frontend/test/of_rewrite_to_custom_call.mlir
This pull request:
- add attr eps_outside_sqrt for l2_norm
- add conversion pattern in onnx-frontend
=> [onnx] add eps_outside_sqrt for l2_norm

compiler/include/byteir-c/Translation.h, compiler/include/byteir/Utils/ModuleUtils.h, compiler/lib/CAPI/Translation.cpp, compiler/lib/Utils/ModuleUtils.cpp, compiler/python/ByteIRModules.cpp, compiler/python/test/api/test_py_api.py
* register `merge_two_modules`.
* throw exception in pybind11 when meet failures.
=> [compiler] register merge_two_modules in python binding

frontends/torch-frontend/CMakeLists.txt, frontends/torch-frontend/TorchMLIR.cmake, frontends/torch-frontend/scripts/build_and_test.sh, frontends/torch-frontend/torch-frontend/python/CMakeLists.txt, frontends/torch-frontend/torch-frontend/python/setup.py, frontends/torch-frontend/torch-frontend/python/torch_frontend/__init__.py, frontends/torch-frontend/torch-frontend/python/torch_frontend/_mlir_libs/_site_initialize_0.py, frontends/torch-frontend/torch-frontend/python/torch_frontend/_torch_frontend_registry.py, frontends/torch-frontend/torch-frontend/python/torch_frontend/compile.py
* split `torch_mlir` from `torch_frontend`, change `torch_frontend.torch_mlir` to `torch_frontend;torch_mlir`
=> [torch-frontend] refactor building method when involving torch-mlir

compiler/include/byteir/Dialect/Lccl/LcclOps.td, compiler/test/Dialect/Ccl/ccl_bufferize.mlir
Added side effects to lccl's op and rewrite the bufferize test using custom format.
=> [compiler]add lccl op side-effect.

frontends/torch-frontend/scripts/build_and_test.sh, frontends/torch-frontend/torch-frontend/python/CMakeLists.txt, frontends/torch-frontend/torch-frontend/python/setup.py
disable jit_ir_importer will make torch-frontend get rid of dependency on specific torch version.
=> [torch-frontend] support build without jit_ir_importer

compiler/lib/CAPI/Translation.cpp, compiler/lib/Dialect/Byre/Transforms/Serial.cpp, compiler/test/lib/Transformation/TestByreSerialRoundtrip.cpp, frontends/torch-frontend/torch-frontend/python/torch_frontend/__init__.py
* fix UAF: `BytecodeWriterConfig` accepts a `StringRef`.
* export torch_frontend.DebugType
=> [compiler] fix UAF on getBytecodeProducerString()

frontends/torch-frontend/third_party/patches/fx_list_return.patch
This PR allows FxImporter to parse operators that return list of tensors, such as aten,unbind.int and aten.split.
NOTE: This is a temporary patch, we should remove it once [this torch-mlir PR](https://github.com/llvm/torch-mlir/pull/3031) is merged.
=> [torch-frontend][FxImporter]: support parsing ops returning list

frontends/torch-frontend/scripts/envsetup.sh, frontends/torch-frontend/third_party/patches/fx_list_return.patch, frontends/torch-frontend/torch-frontend/include/torch-frontend/Pipelines/Pipelines.h, frontends/torch-frontend/torch-frontend/lib/Pipelines/CMakeLists.txt, frontends/torch-frontend/torch-frontend/lib/Pipelines/Pipelines.cpp, frontends/torch-frontend/torch-frontend/python/test/test_torchscript/test_byteir_customcall_ops.py, frontends/torch-frontend/torch-frontend/python/test/test_torchscript/test_model.py, frontends/torch-frontend/torch-frontend/python/test/test_torchscript/test_ops.py, frontends/torch-frontend/torch-frontend/python/test/test_torchscript/test_torch_custom_ops.py, frontends/torch-frontend/torch-frontend/python/torch_frontend/__init__.py, frontends/torch-frontend/torch-frontend/python/torch_frontend/compile.py
* update torch-mlir to upstream main
* remove deprecated `convert_to_mhlo_via_torch_mlir`, use `compile` instead
=> [torch-frontend] update torch-mlir

compiler/lib/Conversion/ToLinalg/MemrefCopyToLinalg.cpp, compiler/test/Conversion/ToLinalg/memrefcopyToLinalg.mlir
viewLikeOp may have dynamic shape, size/shape/.. may be results of other ops. 
All dependent ops should be outlining when create `memref_copy_kernel`.
=> [compiler] support dynamic shape for memrefcopyToLinalg

compiler/lib/Dialect/mhlo/Transforms/GenericFusion.cpp, compiler/lib/Pipelines/GPU/ReductionCodegen.cpp, compiler/lib/Pipelines/LinalgTensorOpt.cpp, tests/numerical_test/torch_e2e_testing/test_suite/basic.py
This PR fixs three bugs, which are
1) padding the last dim of the input tensor as a multiple of wapsize.
2) adding createLinalgFoldUnitExtentDimsPass before tiling the tersor to blocks to avoid that linalg.generic has several reduction dim and can not be collapsed (The reason is not clear temporary).
3) avoiding to set a reduction attribute to those reduce op which only reduces on dimensions with a size of 1.
=> [compiler] fix some bug for reduction

tests/numerical_test/torch_dynamo_e2e_testing/test_suite/test_flash_attn.py
* so that if someone doesn't need to run these testcases, it is not necessary to install `flash_attn`.
=> [e2e] hidden flash_attn into testcase

compiler/lib/Dialect/mhlo/Analysis/DimFromBroadcast.cpp
=> [compiler] fix coredump in DimFromBroadcast

compiler/include/byteir/Dialect/GPU/CMakeLists.txt, compiler/include/byteir/Dialect/GPU/TransformOps/CMakeLists.txt, compiler/include/byteir/Dialect/GPU/TransformOps/GPUExtTransformOps.h, compiler/include/byteir/Dialect/GPU/TransformOps/GPUExtTransformOps.td, compiler/include/byteir/Dialect/GPU/TransformOps/Utils.h, compiler/lib/CAPI/Dialects.cpp, compiler/lib/Dialect/GPU/CMakeLists.txt, compiler/lib/Dialect/GPU/TransformOps/CMakeLists.txt, compiler/lib/Dialect/GPU/TransformOps/GPUExtTransformOps.cpp, compiler/lib/Dialect/GPU/TransformOps/Utils.cpp, compiler/test/Dialect/GPU/transform-gpu-failing.mlir, compiler/test/Dialect/GPU/transform-map-forall-to-blocks.mlir, compiler/test/Dialect/GPU/transform-map-nested-forall-to-threads.mlir, compiler/tools/byteir-opt/CMakeLists.txt, compiler/tools/byteir-opt/byteir-opt.cpp
- add MapNestedForallToThreadsExtOp
- add MapForallToBlocksExtOp
=> [compiler] extension of gpu transformOp

compiler/include/byteir/Dialect/mhlo/Passes.td, compiler/include/byteir/Dialect/mhlo/Transforms/HloFuser.h, compiler/lib/Dialect/mhlo/CMakeLists.txt, compiler/lib/Dialect/mhlo/Transforms/ReduceWindowFusion.cpp, compiler/lib/Pipelines/HloOpt.cpp, compiler/test/Dialect/Mhlo/transforms/reduceFusion.mlir
* because there is another ReductionFusionPass. The name `ReduceFusion` is confusing.
* remove `ReduceFusion` from `HloOpt` as it's unsupported in current pipeline.
* add `UnfuseBatchNorm` to `HloOpt`, so that https://github.com/bytedance/byteir/issues/269 could be resolved.
=> [compiler] rename ReduceFusion to ReduceWindowFusion

frontends/torch-frontend/torch-frontend/python/torch_frontend/compile.py
* to reduce compiling time when compile_dynamo_model()
=> [torch-frontend] disable shape/dtype infer in compile_dynamo_model

runtime/lib/backends/nccl/device/distributed_backend_nccl.cc, runtime/test/backends/nccl/providers/test_distributed_session.cc, runtime/test/test_files/Distributed/broadcast2.mlir
Origin case will fail in this case:
```
byre.compute @nccl.Broadcast(%arg0) {replica_group = [2, 0, 3]} : memref<8xf32, "cuda">
```
As root == 2, but after ncclCommSplit, the new rank will be "1, 0, 2". So it will fail because the wrong root is appointed.
=> [CCL] Fix broadcast

frontends/torch-frontend/torch-frontend/python/test/test_attn_rewrite.py
Usage: `pytest -m "not attention_rewriter"` to not run these testcases.
=> [torch-frontend] mark attention rewriter test

compiler/lib/Dialect/Linalg/Transforms/LinalgPromotion.cpp, compiler/test/Dialect/Linalg/linalg-promotion-epilogue-fusion.mlir
Analysis of the linalg.copy op which copies shared memory back to global memory and fuses the linalg.generic after it. Add an example of fused matmul and relu.
=> [GEMM Codegen] Add epilogue fusion support.

compiler/lib/Dialect/MemRef/Transforms/RemoveCopy.cpp
=> [compiler] fix missing return value in removeCopy

frontends/torch-frontend/torch-frontend/python/torch_frontend/byteir_backend/inner_compile.py, tests/numerical_test/execute.py, tests/numerical_test/profiler.py
=> [e2e] add profiler entry for single stablehlo/mhlo file

compiler/include/byteir/Analysis/ShapeAnalysis.h, compiler/include/byteir/Dialect/Shape/IR/ShapeExtBase.td, compiler/include/byteir/Dialect/Shape/Passes.td, compiler/include/byteir/Dialect/mhlo/Analysis/ShapeAnalysis.h, compiler/include/byteir/Dialect/mhlo/Passes.td, compiler/lib/Analysis/ShapeAnalysis.cpp, compiler/lib/Dialect/Shape/CMakeLists.txt, compiler/lib/Dialect/Shape/IR/ShapeExtOps.cpp, compiler/lib/Dialect/Shape/Transforms/InsertTieShape.cpp, compiler/lib/Dialect/Shape/Transforms/PassDetail.h, compiler/lib/Dialect/mhlo/Analysis/ShapeAnalysis.cpp, compiler/lib/Dialect/mhlo/CMakeLists.txt, compiler/lib/Dialect/mhlo/Transforms/BoundedShapeInference.cpp, compiler/lib/Dialect/mhlo/Transforms/PassDetail.h, compiler/lib/Dialect/mhlo/Transforms/StaticShapeInference.cpp, compiler/lib/Transforms/CMakeLists.txt, compiler/lib/Transforms/GraphClusteringByDevice.cpp, compiler/test/lib/Analysis/TestPrintShapeAnalysis.cpp
1. support nested region such as scf.if for GraphClusteringByDevice pass
2. scf.if output type compatibility
a. do not insert shape_ext.TieOp after a mhlo.ConvertOp when Convert static shape op to dynamic shape op
b. set return type for thenBlock and elseBlock for scf.ifOp when the shape of the return value of scf.ifOp can be deduced
by shape_ext.tieOp
c. set bounded shape for thenBlock and elseBlok of scf.ifOp to meet the compatibility requirements of scf.ifop return
types
3. decoupling static shape analysis from bounded shape analysis
=> [compiler] fix DeviceGraphCluster for if op

frontends/onnx-frontend/onnx-frontend/src/Conversion/OFRewriteToCustomCall.cpp
CreateSqueezedValue should only squeeze value whose shape contains all ones except the dim to squeeze. Added a check
=> [onnx] fix squeezed value

compiler/include/byteir/Conversion/Passes.td, compiler/include/byteir/Conversion/ToLinalg/ToLinalg.h, compiler/include/byteir/Pipelines/LinalgTensorOpt.h, compiler/lib/Conversion/ToLinalg/HloToLinalg.cpp, compiler/lib/Pipelines/LinalgTensorOpt.cpp, compiler/python/byteir/compile.py, compiler/test/Conversion/ToLinalg/hloConvertToLinalg.mlir, tests/numerical_test/execute.py, tests/numerical_test/mlir_tests/cpu_ops/convert_f32_i32_special_val.mlir
1. on x86_64, [inf, -inf, nan] will be converted to [INT32_MIN, INT32_MIN, INT32_MIN] due to UB. However, on arm_aarch64/nvgpu, [inf, -inf, nan] will be converted to [INT32_MAX, INT32_MIN, 0].
2. so we add compare and select during HloToLinalg and add target & arch option to control it.
=> [compiler] fix inf/nan convert to i32 on x86_64 arch

frontends/tf-frontend/external/patches/tensorflow/for_gcc_8_5.patch, frontends/tf-frontend/external/patches/tensorflow/tf_mkl.patch
=> [tf-frontend] fix for gcc8.5

compiler/lib/Dialect/MemRef/Transforms/RemoveCopy.cpp
this pass tries to remove redundant copyOp. When some of these copyOps have W.R deps, the max number of iterations would lgt the default(10) value. Just set to 20 to bypass the current cases.
TODO: solve this issue more generally.
=> [compiler] fix remove copy max iteration error.

compiler/python/byteir/dialects/cat/ait_cache.py, frontends/torch-frontend/torch-frontend/python/torch_frontend/byteir_backend/compilation_cache.py
=> [compiler & torch-frontend] unify default cache dir to ~/.byteir

tests/compatibility_test/execute.py, tests/compatibility_test/main.py, tests/compatibility_test/reporting.py
so that it could catch runtime error
=> [e2e] add execution error in compatibility test

.github/workflows/torch-frontend-ci.yaml, frontends/README.md, frontends/torch-frontend/README.md, frontends/torch-frontend/build-requirements.txt, frontends/torch-frontend/examples/demo/README.md, frontends/torch-frontend/examples/demo/requirements.txt, frontends/torch-frontend/requirements.txt, frontends/torch-frontend/scripts/build.sh, frontends/torch-frontend/scripts/build_and_test.sh, frontends/torch-frontend/scripts/envsetup.sh, frontends/torch-frontend/test-requirements.txt, frontends/torch-frontend/torch-cpu-requirements.txt, frontends/torch-frontend/torch-cuda-requirements.txt, tests/build_and_test_e2e.sh
* split `requirements.txt` to `build-requirements.txt`, `test-requirements.txt`, `torch-cpu-requirements.txt` and `torch-cuda-requirements.txt`
=> [torch-frontend] refator requirements.txt

compiler/python/byteir/__init__.py, compiler/python/byteir/compile.py, runtime/python/brt/backend.py, tests/numerical_test/execute.py
=> [runtime] add BRTBackend, add byteir.compile_from_string

frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToStablehloExt.cpp, frontends/torch-frontend/torch-frontend/python/test/test_torchscript/test_ops.py
* support expand: (3, 1) => (3, 4) && (3, 1) => (2, 2, 3, 4) && (,) => (3, 4)
=> [torch-frontend] fix lowering of aten.expand_as

frontends/torch-frontend/torch-frontend/python/CMakeLists.txt, frontends/torch-frontend/torch-frontend/python/setup.py
so that it could reduce total size of wheel.
=> [torch-frontend] only link aggregateCAPI with version

compiler/lib/Dialect/mhlo/Transforms/DecomposeMhloCustomCallOps.cpp, compiler/test/Dialect/Mhlo/transforms/DecomposeMhloCustomCallOps.mlir, tests/numerical_test/mlir_tests/cpu_ops/custom_call_byteir_softmax.mlir
=> [compiler] support decompose of byteir.softmax

compiler/include/byteir-c/Translation.h, compiler/include/byteir/Utils/ModuleUtils.h, compiler/lib/CAPI/Translation.cpp, compiler/lib/Utils/ModuleUtils.cpp, compiler/python/ByteIRModules.cpp, compiler/python/test/api/test_py_api.py
as title  
mapping argument describe how func0's outputs map to func1's inputs
* example1: func0 and func1 one-one mapping => [0, 1, 2, ....]
* example2: func0's first and second output mapping to func1 => [1, 0, -1]
=> [compiler] support merge two modules by mapping

frontends/onnx-frontend/third_party/patches/OnnxMlirONNXToStablehloCommon.patch
- fix `getShapedValue` in ONNXToStablehloCommon to support APFloat with fp16 input
=> fix getShapedFloat with APFloat value

frontends/torch-frontend/third_party/patches/fx_importer.patch, frontends/torch-frontend/torch-frontend/python/test/test_fximporter/test_ccl.py, frontends/torch-frontend/torch-frontend/python/test/test_fximporter/utils.py
=> fix: fix ccl op signature mismatch when updating torch to 2.4 or above

frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToCustomCall.cpp, frontends/torch-frontend/torch-frontend/python/test/test_torchscript/test_byteir_customcall_ops.py
=> [torch-frontend] lowerint aten.upsample_bilinear to byteir.resize

frontends/onnx-frontend/third_party/patches/OnnxMlirDialectRewrite.patch
fix onnx-mlir upstream pattern:  *PropagateConstantScalingInAttentionLayerPattern*, which fuse attention pattern and do constant propagation. 
This pattern has not consider Matmul with multi uses.
=> [onnx-mlir] fix attention const propagation pattern

compiler/include/byteir/Dialect/mhlo/DynamicShapeOpRegister/Register.h, compiler/test/Transforms/boundedShapeInference.mlir, compiler/test/Transforms/shapeReification.mlir, compiler/test/Transforms/staticShapeInference.mlir, frontends/tf-frontend/tf_mlir_ext/tests/mhlo_legalize_tf_ext.mlir, frontends/tf-frontend/tf_mlir_ext/transforms/mhlo_legalize_tf_ext.cc
1. [tf-frontend] fix for tf.StridedSlice
2. [compiler] remove shape infer function for tf.BatchMatMul and tf.StridedSlice
=> [compiler] remove shape infer function for tf.BatchMatMul and tf.StridedSlice
