bytedance/byteir

compiler/test/Dialect/Linalg/transform-op-fuse.mlir

Add multi stops test coverage for fuse-ext

Add multi stops test coverage for fuse-ext

---

compiler/lib/Dialect/Linalg/Transforms/Transforms.cpp
compiler/test/Dialect/Linalg/fuse-attention.mlir
compiler/test/Dialect/Linalg/transform-op-fuse.mlir

Before this patch, when applying `--transform-dialect-interpreter` on 
```
#map = affine_map<(d0) -> (d0)>
func.func @multi_results_one_in_tile_fuse_path_one_in_terminator(%arg0: tensor<1024xf32>, %arg1: tensor<1024xf32>, %arg2: tensor<1024xf32>) -> (tensor<1024xf32>, tensor<1024xf32>) {
%0 = tensor.empty() : tensor<1024xf32>
%1:2 = linalg.generic {__g0__, indexing_maps = [#map, #map, #map, #map], iterator_types = ["parallel"]} ins(%arg0, %arg1 : tensor<1024xf32>, tensor<1024xf32>) outs(%0, %0 : tensor<1024xf32>, tensor<1024xf32>) {
^bb0(%in_0: f32, %in_1: f32, %out_0: f32, %out_1: f32):
%2 = arith.addf %in_0, %in_1 : f32
%3 = arith.subf %in_0, %in_1 : f32
linalg.yield %2, %3 : f32, f32
} -> (tensor<1024xf32>, tensor<1024xf32>)
%2 = linalg.generic {__root__, __g1__, indexing_maps = [#map, …
```

[Linalg] fix intermediate results cleaning in fuse-ext

---

compiler/include/byteir/Dialect/mhlo/Transforms/CanonicalizeExt.h
compiler/lib/Dialect/mhlo/Transforms/CanonicalizeExt.cpp
compiler/lib/Transforms/CanonicalizeExt.cpp

Allow users to filter these patterns by name.

[compiler] refactor anonymous patterns to named patterns

---

compiler/include/byteir/Dialect/mhlo/DynamicShapeOpRegister/Register.h
compiler/include/byteir/Dialect/mhlo/Util/CustomCallUtil.h
compiler/include/byteir/Utils/Utils.h
compiler/lib/Analysis/ShapeAnalysis.cpp
compiler/lib/Conversion/ToLinalg/UnrealizedCastToLinalg.cpp
compiler/lib/Dialect/Ace/Transforms/BufferizableOpInterfaceImpl.cpp
compiler/lib/Dialect/Cat/IR/CatDialect.cpp
compiler/lib/Dialect/mhlo/Analysis/ShapeAnalysis.cpp
compiler/lib/Dialect/mhlo/CMakeLists.txt
compiler/lib/Dialect/mhlo/DynamicShapeOpRegister/Repeat.cpp
compiler/lib/Dialect/mhlo/DynamicShapeOpRegister/StridedSlice.cpp
compiler/lib/Dialect/mhlo/DynamicShapeOpRegister/Where.cpp
compiler/lib/Dialect/mhlo/Transforms/CanonicalizeExt.cpp
frontends/onnx-frontend/onnx-frontend/src/Conversion/OFRewriteToCustomCall.cpp
frontends/onnx-frontend/onnx-frontend/src/Conversion/OFRewriteToCustomCall.td
frontends/onnx-frontend/onnx-frontend/test/of_rewrite_to_custom_call.mlir
runtime/lib/core/framework/execution_plan.cc

[Sync] internal a6016645...58cf8dba
[compiler] Add FoldScatterWithUpdate pattern
code clean with clang build
[compiler] infer bounded shape for byteir.repeat and tf.StridedSlice
[runtime] support group copy dependency
[onnx-frontend] add layernorm pattern with no eps

[Sync] enhance bounded shape infer and code cleaning

---

.github/workflows/compiler-and-runtime-build.yml
.github/workflows/e2e_test.yaml
.github/workflows/torch-frontend-ci.yml
frontends/tf-frontend/README.md

Add more `paths` and `paths-ignore` to ci.

[ci] enhance ci with more paths

---

.github/workflows/onnx-frontend-ci.yaml

This pull request rename onnx-frontend-ci.yml to onnx-frontend-ci.yaml

[ci] fix onnx yaml name

---

compiler/python/byteir/dialects/cat/ir_processor.py

* to avoid ci failed sometimes.

[compiler] add fix for cat-ir-processor back

---

frontends/torch-frontend/third_party/patches/communication_op.patch
frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToCustomCall.cpp
frontends/torch-frontend/torch-frontend/python/torch_frontend/__init__.py
frontends/torch-frontend/torch-frontend/python/torch_frontend/convert_to_mhlo.py
frontends/torch-frontend/torch-frontend/test/Conversion/ConvertTorchToCustomCall.mlir

* first PR to support communication ops
* add compile_exported_program api
* lowering to stablehlo.custom_call

[torch-frontend] add patch of torch functional communication ops

---

.github/workflows/compiler-and-runtime-ci.yaml
.github/workflows/e2e_test.yaml
.github/workflows/format-check.yaml
.github/workflows/onnx-frontend-ci.yaml
.github/workflows/tf-frontend-ci.yaml
.github/workflows/torch-frontend-ci.yaml

* require pull request must rebase the latest `main` branch, so not need to run ci after push to `main`

[ci] remove ci after push

---

frontends/tf-frontend/scripts/build_and_test.sh

print message when bazel test failed

[tf-frontend] print test failed message

---

frontends/tf-frontend/tf_mlir_ext/numerical/numerical_test.py
frontends/tf-frontend/tf_mlir_ext/numerical/rewrite_to_custom_call.mlir
frontends/tf-frontend/tf_mlir_ext/tests/rewrite_to_custom_call.mlir
frontends/tf-frontend/tf_mlir_ext/transforms/rewrite_to_custom_call.cc
frontends/tf-frontend/tf_mlir_ext/transforms/rewrite_to_custom_call.td

[tf-frontend] add gelu fusion pattern

---

frontends/tf-frontend/WORKSPACE
frontends/tf-frontend/byteir/Dialect/Ace/AceBase.td
frontends/tf-frontend/byteir/Dialect/Ace/AceDialect.cpp
frontends/tf-frontend/byteir/Dialect/Ace/AceDialect.h
frontends/tf-frontend/byteir/Dialect/Ace/AceOps.td
frontends/tf-frontend/byteir/ace.BUILD
frontends/tf-frontend/byteir/workspace.bzl
frontends/tf-frontend/tf_mlir_ext/transforms/BUILD
frontends/tf-frontend/tools/BUILD

build ace_dialect using external source code

[tf-frontend] build ace_dialect using external source code

---

compiler/README.md
runtime/README.md

* change readme's description about llvm-project.

[*] fix readme's llvm description

---

frontends/torch-frontend/requirements.txt
frontends/torch-frontend/torch-frontend/python/test/test_attn_rewrite.py
frontends/torch-frontend/torch-frontend/python/test/test_ccl.py
frontends/torch-frontend/torch-frontend/python/test/utils.py
frontends/torch-frontend/torch-frontend/python/torch_frontend/compile.py

As mentioned in title, this PR add FileCheck test for pytorch collective operators, like reduce_scatter, all_reduce, all_gather.

[torch-frontend] add test for collective operators

---

LICENSE

Change the license format to unchanged Apache 2.0

[doc] fix license format.

---

compiler/python/byteir/compile.py
frontends/torch-frontend/torch-frontend/python/torch_frontend/compile.py

[*] make code more pythonic

---

.github/ISSUE_TEMPLATE/bug.md
.github/ISSUE_TEMPLATE/feature-request.md
.github/ISSUE_TEMPLATE/question.md

[github] Update issue templates

---

frontends/torch-frontend/torch-frontend/python/test/test_attn_rewrite.py

[torch-frontend] relax attn test's atol and rtol

---

frontends/torch-frontend/third_party/patches/generated_torch_ops_td.patch
frontends/torch-frontend/third_party/patches/torch_ops_cpp.patch

[torch-frontend] add folder for aten.clone

---

compiler/dialects/include/byteir/Dialect/Ccl/IR/CclOps.td
compiler/lib/Dialect/Ccl/Transforms/CclMoveDown.cpp

* ccl ops do not have pure trait, they should not be eliminated when they do not be used.

[ccl] remove pure trait from ccl ops

---

compiler/lib/Dialect/MemRef/Transforms/RemoveCopy.cpp
compiler/test/Dialect/MemRef/removeCopy.mlir

We found bugs in some cases, which I fixed. Please check the test for details.

[compiler] fix remove-copy

---

compiler/include/byteir-c/Translation.h
compiler/lib/CAPI/Translation.cpp
compiler/python/ByteIRModules.cpp
compiler/python/byteir/_mlir_libs/_site_initialize_0.py
compiler/python/test/api/test_py_api.py
scripts/compiler/build_and_test.sh

* add `serialize_byre` and `deserialize_byre` api.
* add testcases for pytest.

[compiler] register serialization api in python binding

---

runtime/test/backends/cuda/providers/default/kernel/flash_attn_bwd_test.cc
runtime/test/backends/cuda/providers/default/kernel/flash_attn_fwd_test.cc
scripts/runtime/build_and_test.sh

* otherwise that `bash ../scripts/runtime/build_and_test.sh --python`'s `--python` doesn't work.
* fix memory leak in runtime gtest.

[runtime] fix build script

---

compiler/dialects/include/byteir/Dialect/Ccl/IR/CclOps.td
compiler/test/Dialect/Ccl/ccl_canonicalize.mlir
compiler/test/Dialect/Ccl/ops.mlir
compiler/test/Dialect/Linalg/transform-op-fuse-multi-root.mlir

Previously there was only custom format for broadcast, now added the rest.

[compiler] add custom format for ccl ops

---

.github/workflows/compiler-and-runtime-ci.yaml
.github/workflows/daily_ci.yaml
.github/workflows/e2e_test.yaml
.github/workflows/format-check.yaml
.github/workflows/onnx-frontend-ci.yaml
.github/workflows/tf-frontend-ci.yaml
.github/workflows/torch-frontend-ci.yaml
frontends/onnx-frontend/scripts/envsetup.sh
frontends/tf-frontend/scripts/build_and_test.sh
frontends/torch-frontend/scripts/envsetup.sh
scripts/compiler/build_and_test.sh
scripts/e2e/build_and_test_e2e.sh
scripts/prepare.sh

This pull request:
- make github actions run in docker containers
- fix some of the broken paths
- install required pip wheels

[ci] Run on docker

---

compiler/lib/CAPI/Translation.cpp

[compiler] use BYRE as serialization producer string

---

frontends/onnx-frontend/onnx-frontend/src/Compiler/OFCompilerUtils.cpp

This pull request makes onnx-frontend keep the shape info in original model when bs of the static input tensor is the same as the replacing value or static bs but not forceSetBatchSize.

[onnx] keep shape for static bs

---

README-zh_cn.md
README.md
frontends/torch-frontend/examples/inference/infer_resnet.py
frontends/torch-frontend/examples/inference/infer_tinybert.py

[*] update README and some examples

---

compiler/lib/Conversion/HloToByreTensor/HloToByreTensor.cpp
compiler/test/Conversion/HloToByreTensor/compute_ops.mlir

[compiler] support dynamic shape for concatOp conversion

---

frontends/torch-frontend/torch-frontend/lib/Pipelines/CMakeLists.txt

[torch-frontend] update torch-mlir

---

frontends/tf-frontend/tf_mlir_ext/pipelines/customized_tf_to_mhlo.cc
frontends/tf-frontend/tf_mlir_ext/pipelines/customized_tf_to_mhlo.h
frontends/tf-frontend/tf_mlir_ext/pipelines/passes.td
frontends/tf-frontend/tools/tf_frontend_main.cc

support stop after convert to tf dialect

[tf-frontend] support stop after convert to tf dialect

---

compiler/lib/Dialect/mhlo/Transforms/CanonicalizeExt.cpp
compiler/test/Transforms/canonicalizeExt.mlir

[compiler] simplify reduce to reshape

---

compiler/include/byteir/Dialect/mhlo/Util/Util.h
compiler/lib/Dialect/mhlo/Transforms/CanonicalizeExt.cpp
compiler/lib/Dialect/mhlo/Util/Util.cpp

[compiler] add isReglurReduceOp util function

---

frontends/onnx-frontend/onnx-frontend/src/Conversion/OFRewriteToCustomCall.cpp

This PR removes assertion of keepdims for argmax/argmin

[onnx] remove assert keepdims for argmax/argmin

---

runtime/lib/backends/cpu/providers/default/cpu_provider.cc
runtime/lib/backends/cpu/providers/default/custom_call/repeat.cc
runtime/lib/backends/cpu/providers/default/custom_call/repeat.h
runtime/test/backends/cpu/providers/default/kernel/repeat_test.cc
runtime/test/common/models.cc
runtime/test/include/brt/test/common/models.h

add custom_call byteir.repeat op_kernel on cpu

[runtime] add custom_call byteir.repeat op_kernel on cpu

---

runtime/cmake/brt_unittests.cmake
runtime/include/brt/backends/cpu/device/cpu_device_api.h
runtime/include/brt/backends/cuda/device/cuda_device_api.h
runtime/include/brt/backends/device_api.h
runtime/include/brt/core/context/execution_frame.h
runtime/include/brt/core/distributed/distributed_session.h
runtime/include/brt/core/framework/device_api.h
runtime/include/brt/core/framework/execution_plan.h
runtime/include/brt/core/framework/memory_info.h
runtime/include/brt/core/session/request_context.h
runtime/include/brt/core/session/session.h
runtime/lib/backends/cpu/device/cpu_device_api.cc
runtime/lib/core/context/execution_frame.cc
runtime/lib/core/framework/device_api.cc
runtime/lib/core/session/request_context.cc
runtime/python/src/module.cc
runtime/test/backends/cpu/providers/default/request_context_test.cc
runtime/test/backends/cuda/providers/default/request_context_test.cc
runtime/test/context/exec_frame_test.cc

[runtime] support binding arg with different ownership

---

compiler/lib/Transforms/CanonicalizeExt.cpp

* pass `foldLimit` into pass contructor.

[compiler] fix canonicalize-ext

---

compiler/python/byteir/compile.py
compiler/python/byteir/tools/compiler.py

* add `gpu_type` argument in python entry
* support offline compilation.

[compiler] add gpu_type argument in python

---

compiler/python/byteir/compile.py
compiler/python/byteir/tools/compiler.py
compiler/python/test/api/test_py_api.py

* construct compilation pipeline for cpu

[compiler] add cpu target compiler

---

runtime/lib/backends/cpu/device/cpu_work_queue.cc
runtime/lib/core/context/execution_frame.cc
runtime/test/backends/cpu/providers/default/request_context_test.cc
runtime/test/backends/cuda/providers/default/request_context_test.cc

[runtime] fix bind arg

---

compiler/python/CMakeLists.txt
compiler/python/byteir/_backend_registry.py
compiler/python/byteir/compile.py
compiler/python/byteir/registry.py
runtime/include/brt/core/session/session.h
runtime/lib/core/session/session.cc
runtime/python/src/module.cc
tests/numerical_test/execute.py
tests/numerical_test/main.py
tests/numerical_test/mlir_tests/cpu_ops/add2.mlir
tests/numerical_test/mlir_tests/cpu_ops/convert_f32_f16.mlir

* add cpu device in pysession
* add simple mlir test case

[runtime] add cpu device for PySession

---

compiler/lib/Dialect/Linalg/Transforms/LinalgCollapseLoops.cpp
compiler/test/Dialect/Linalg/linalg-collapse-loops.mlir

[compiler] collapse loops with dynamic shape

---

frontends/onnx-frontend/onnx-frontend/src/Compiler/OFCompilerUtils.cpp

* ref to `https://github.com/onnx/onnx/blob/main/docs/IR.md#tensor-definition`
* replace all negative dim with null, as onnx ShapeInfer does not deal negative dim well in `CheckTensorShapesAndTypes`

[onnx-frontend] fix invalid dim value in Graph

---

frontends/tf-frontend/tf_mlir_ext/tests/mhlo_legalize_tf_ext.mlir
frontends/tf-frontend/tf_mlir_ext/transforms/mhlo_legalize_tf_ext.cc
runtime/lib/backends/cpu/providers/default/cpu_provider.cc
runtime/test/backends/cpu/providers/default/kernel/repeat_test.cc

comment out convertRoundOp pattern

[tf-frontend] comment out convertRoundOp pattern

---

compiler/include/byteir-c/Translation.h
compiler/lib/CAPI/Translation.cpp
compiler/python/ByteIRModules.cpp
compiler/python/test/api/test_py_api.py

[compiler] add translate_to_llvmir python api

---

compiler/include/byteir/Utils/AttrUtils.h
compiler/lib/Transforms/FuncTag.cpp
compiler/lib/Utils/AttrUtils.cpp
compiler/python/byteir/compile.py

[compiler] enable dump mlirbc in cpu pipeline

---

compiler/python/CMakeLists.txt
compiler/python/byteir/__init__.py
compiler/python/byteir/_byteir_registry.py
compiler/python/byteir/compile.py
compiler/python/test/api/test_py_api.py

[compiler] refactor byteir.compile

---

compiler/include/byteir/Dialect/mhlo/Passes.h
compiler/include/byteir/Dialect/mhlo/Passes.td
compiler/include/byteir/Dialect/mhlo/Transforms/HloFuser.h
compiler/include/byteir/Dialect/mhlo/Transforms/HloSimplify.h
compiler/lib/Dialect/mhlo/CMakeLists.txt
compiler/lib/Dialect/mhlo/Transforms/CanonicalizeExt.cpp
compiler/lib/Dialect/mhlo/Transforms/HloSimplify.cpp
compiler/lib/Pipelines/HloOpt.cpp
compiler/test/Dialect/Mhlo/transforms/hloSimplify.mlir
compiler/test/Transforms/CanonicalizeExt/reduce_like.mlir

* add hlo-simplify pass
* move simplify-reduce-to-reshape and reshape-gather to hlo-simplify
* add simplify-slice-broadcast-to-broadcast pattern

[compiler] add hlo-simplify pass

---

compiler/lib/Dialect/mhlo/Transforms/HloSimplify.cpp
compiler/numerical/hlo/hlo_simplify.mlir
compiler/test/Dialect/Mhlo/transforms/hloSimplify.mlir

[compiler] add simplify-dot-general pattern

---

frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToCustomCall.cpp
frontends/torch-frontend/torch-frontend/python/test/test_torchscript/test_ops.py
frontends/torch-frontend/torch-frontend/python/torch_frontend/compile.py
frontends/torch-frontend/torch-frontend/test/Conversion/ConvertTorchToCustomCall.mlir

* not to decompose aten.amax
* update torch-mlir

[torch-frontend] always lowering torch.max()[0] to reduce max

---

frontends/torch-frontend/examples/inference/mixtral/infer_single_mixtral.py
frontends/torch-frontend/examples/inference/mixtral/requirements.txt

[torch-frontend] add mixtral inference code

---

compiler/doc/byteir_mhlo_custom_call.md
frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToCustomCall.cpp
frontends/torch-frontend/torch-frontend/python/test/test_fximporter/test_simple_ops.py
frontends/torch-frontend/torch-frontend/test/Conversion/ConvertTorchToCustomCall.mlir

[torch-frontend] lower aten.nonzero to byteir.non_zero

---

compiler/lib/Conversion/ToLinalg/HloToLinalg.cpp
compiler/lib/Dialect/mhlo/Transforms/HloAggressiveFusion.cpp
compiler/test/CPURunner/repeatCustomCall.mlir
compiler/test/Conversion/ToLinalg/repeatCustomCallToLinalg.mlir

convert byteir.repeat to linalg and add test case

[compiler] convert byteir.repeat to linalg

---

frontends/tf-frontend/tf_mlir_ext/tests/mhlo_legalize_tf_ext.mlir
frontends/tf-frontend/tf_mlir_ext/transforms/mhlo_legalize_tf_ext.cc

[tf-frontend] open convertRoundOp pattern

---

frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToCustomCall.cpp
frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToStablehloExt.cpp
frontends/torch-frontend/torch-frontend/lib/Transforms/FuseOpOnTorchPattern.td
frontends/torch-frontend/torch-frontend/lib/Transforms/RewriteCustomOp.cpp
frontends/torch-frontend/torch-frontend/lib/Utils/ConvertOpFolder.cpp

* as llvm has deprecated cast/dyn_cast method.

[torch-frontend] use global cast/dyn_cast

---

runtime/include/brt/core/context/execution_frame.h

[runtime] update execution_frame.h

---

compiler/include/byteir/Conversion/GPUToNVVM/GPUToNVVM.h
compiler/include/byteir/Conversion/Passes.td
compiler/include/byteir/Pipelines/GPU/NVVMCodegen.h
compiler/include/byteir/Target/PTX/Passes.h
compiler/lib/Conversion/GPUToNVVM/GPUToNVVM.cpp
compiler/lib/Pipelines/GPU/NVVMCodegen.cpp
compiler/lib/Target/PTX/GPUKernelToPTX.cpp
compiler/lib/Target/PTX/TranslateToPTX.cpp
compiler/python/byteir/compile.py

* temp fix `arith::min(max)imum` with nvgpu which lower than sm_80
* add options to dump llir

[compiler] fix min(max)imum in sm_70

---

compiler/include/byteir/Dialect/mhlo/Transforms/GenericFusionCommon.h
compiler/include/byteir/Dialect/mhlo/Transforms/HloFuser.h
compiler/include/byteir/Pipelines/HloOpt.h
compiler/lib/Dialect/mhlo/Transforms/CatFusion.cpp
compiler/lib/Dialect/mhlo/Transforms/GenericFusion.cpp
compiler/lib/Dialect/mhlo/Transforms/HloAggressiveFusion.cpp
compiler/lib/Pipelines/HloOpt.cpp
compiler/test/Dialect/Mhlo/transforms/elementFusion.mlir

* support disable-elementwise-fusion option in ElementwiseFusionPass.
* refactor GenericFusionPass to support subtype's option.

[compiler] support disable-elementwise-fusion in ElementwiseFusionPass

---

compiler/include/byteir/Dialect/mhlo/Transforms/HloFuser.h
compiler/include/byteir/Pipelines/HloOpt.h
compiler/lib/Dialect/mhlo/Transforms/HloAggressiveFusion.cpp
compiler/lib/Pipelines/HloOpt.cpp
compiler/test/Dialect/Mhlo/transforms/aggressiveFusion.mlir

[compiler] support disable-fusion in hlo-aggressive-fusion

---

frontends/tf-frontend/tf_mlir_ext/transforms/rewrite_to_custom_call.cc

fix bug for creating DenseFPElementsAttr

[tf-frontend] fix bug for creating DenseFPElementsAttr

---

frontends/torch-frontend/third_party/patches/fx_importer.patch

[fix] fix FakeTensor weight in fx_importer

---

compiler/include/byteir/Dialect/mhlo/Transforms/CanonicalizeExt.h
compiler/lib/Dialect/mhlo/Transforms/CanonicalizeExt.cpp
compiler/test/Transforms/CanonicalizeExt/deprecated.mlir

[compiler] canonicalize broadcast to broadcast_in_dim

---

compiler/include/byteir/Dialect/mhlo/Passes.h
compiler/include/byteir/Dialect/mhlo/Transforms/HloFuser.h
compiler/lib/Dialect/mhlo/Transforms/GenericFusion.cpp
compiler/lib/Pipelines/HloOpt.cpp
compiler/test/Dialect/Mhlo/transforms/concatSliceFusion.mlir

[compiler] add mhlo concat slice fusion

---

tests/numerical_test/torch_dynamo_e2e_testing/backend.py

[chore] fix torch dynamo e2e testing

---

compiler/README.md
compiler/lib/Dialect/mhlo/Transforms/GenericFusion.cpp
compiler/python/byteir/tools/compiler.py
runtime/README.md

* add build LLVM instructions to doc

[compiler & runtime] update doc

---

compiler/include/byteir/Dialect/MemRef/Utils/MemEffect.h
compiler/lib/Dialect/MemRef/Transforms/RemoveCopy.cpp
compiler/lib/Dialect/MemRef/Utils/MemEffect.cpp
compiler/test/Dialect/MemRef/removeCopy.mlir

[compiler] fix bug in RemoveCopy

---

compiler/lib/Dialect/mhlo/Transforms/CanonicalizeExt.cpp

[compiler] support splat value in CompareFolder

---

compiler/lib/Pipelines/ByreOpt.cpp

[compiler] add remove-copy pass in byre-opt pipeline

---

compiler/lib/Dialect/MemRef/Transforms/RemoveCopy.cpp
compiler/test/Dialect/MemRef/removeCopy.mlir

[compiler] remove copyOp whose target is arg

---

frontends/torch-frontend/torch-frontend/python/CMakeLists.txt
frontends/torch-frontend/torch-frontend/python/torch_frontend/compile.py
frontends/torch-frontend/torch-frontend/python/torch_frontend/tools/extra_fn.mlir
frontends/torch-frontend/torch-frontend/python/torch_frontend/tools/gen_extra_library.py

so that we could run torch_frontend with custom op in multi-threading or multi-process context.

[torch-frontend] generate extra_fn.mlir before torch_frontend.compile

---

compiler/include/byteir-c/PDLValue.h
compiler/include/byteir/Transforms/ApplyPDLPatterns.h
compiler/include/byteir/Transforms/Passes.h
compiler/include/byteir/Transforms/Passes.td
compiler/include/byteir/Utils/PatternMatch.h
compiler/lib/CAPI/CMakeLists.txt
compiler/lib/CAPI/Dialects.cpp
compiler/lib/CAPI/PDLValue.cpp
compiler/lib/Transforms/ApplyPDLPatterns.cpp
compiler/lib/Transforms/CMakeLists.txt
compiler/lib/Transforms/PassDetail.h
compiler/lib/Utils/CMakeLists.txt
compiler/lib/Utils/PatternMatch.cpp
compiler/python/ByteIRModules.cpp
compiler/python/CMakeLists.txt
compiler/python/byteir/pattern_matches.py
compiler/python/test/api/test_pattern_matches.py
compiler/test/Transforms/ApplyPDLPatterns/Case_0.mlir
compiler/test/Transforms/ApplyPDLPatterns/Pattern_0.mlir

[compiler] introduce python rewrite pattern

---

compiler/lib/Dialect/mhlo/Transforms/CanonicalizeExt.cpp

As title.
Add clamp canonicalize feature:
* replace splat value with scalar
* `clamp(-inf, x, inf) => x`

[compiler] add clamp canonicalize

---

compiler/python/byteir/compile.py
compiler/python/byteir/dialects/cat/ir_processor.py
compiler/python/byteir/dialects/cat/ir_translator/ait_builder.py
compiler/python/byteir/tools/cat_execute.py
compiler/python/byteir/tools/cat_numerical_test.py

* remove dump_ir(), use verbose instead.

[compiler] small refactor for cat ait pipeline

---

frontends/tf-frontend/tf_mlir_ext/numerical/numerical_test.py
frontends/tf-frontend/tf_mlir_ext/numerical/rewrite_to_custom_call.mlir
frontends/tf-frontend/tf_mlir_ext/tests/rewrite_to_custom_call.mlir
frontends/tf-frontend/tf_mlir_ext/transforms/rewrite_to_custom_call.cc
frontends/tf-frontend/tf_mlir_ext/transforms/rewrite_to_custom_call.td

add new parten for layer_norm and l2_norm

[tf-frontend] add new parten for layer_norm and l2_norm

---

.github/workflows/compiler-ci.yaml
.github/workflows/runtime-ci.yaml

[ci] decouple compiler and runtime ci

---

compiler/python/byteir/dialects/cat/ir_processor.py
compiler/python/byteir/dialects/cat/ir_translator/backend/ait_registry.py
compiler/python/byteir/tools/cat_executor.py
frontends/torch-frontend/scripts/build_and_test.sh
frontends/torch-frontend/torch-frontend/python/torch_frontend/compile.py
scripts/compiler/build_and_test.sh

* as title and fix typo & remove useless code

[scripts] add --no-test option in byteir & torch_frontend's build script

---

compiler/include/byteir/Dialect/Byre/ByreDialect.h
compiler/include/byteir/Dialect/Byre/ByreOps.td
compiler/include/byteir/Dialect/Byre/Common.h
compiler/include/byteir/Transforms/Passes.h
compiler/include/byteir/Transforms/Passes.td
compiler/include/byteir/Transforms/ShapeFuncOutlining.h
compiler/lib/Analysis/SideEffect.cpp
compiler/lib/Dialect/Byre/IR/ByreDialect.cpp
compiler/lib/Transforms/CMakeLists.txt
compiler/lib/Transforms/ShapeFuncOutlining.cpp
compiler/test/Transforms/shapeFuncOutlining.mlir

[compiler] add shape-func-outlining pass

---

.github/workflows/e2e_test.yaml
compiler/lib/Dialect/mhlo/Transforms/FuseBMMDimension.cpp
tests/build_and_test_e2e.sh

[e2e] add --no-test when build compiler and torch_frontend in e2e

---

compiler/python/byteir/compile.py
compiler/python/byteir/dialects/cat/ir_processor.py
compiler/python/byteir/utils.py
tests/build_and_test_e2e.sh
tests/numerical_test/execute.py
tests/numerical_test/main.py

* Usage: `python3 tests/numerical_test/main.py --config torch --target cuda -f ReductionParallelModule_basic --mode profile`.
* Support torch e2e testcase to run on cpu.

[e2e] support profile mode

---

compiler/include/byteir/Transforms/ShapeFuncOutlining.h
compiler/lib/Conversion/ToLLVM/GenLLVMConfig.cpp
compiler/lib/Transforms/ShapeFuncOutlining.cpp

[compiler] attach  attr to shape func

---

frontends/torch-frontend/torch-frontend/python/torch_frontend/byteir_backend/compiled_function.py
runtime/python/src/module.cc

[dynamo] group bind args

---

frontends/tf-frontend/tf_mlir_ext/pipelines/customized_tf_to_mhlo.cc
frontends/tf-frontend/tf_mlir_ext/pipelines/customized_tf_to_mhlo.h
frontends/tf-frontend/tf_mlir_ext/pipelines/passes.td
frontends/tf-frontend/tf_mlir_ext/tests/fuse_tf_ops.mlir
frontends/tf-frontend/tf_mlir_ext/transforms/fuse_tf_ops.cc
frontends/tf-frontend/tf_mlir_ext/transforms/fuse_tf_ops.h
frontends/tf-frontend/tf_mlir_ext/transforms/fuse_tf_ops.td
frontends/tf-frontend/tf_mlir_ext/transforms/passes.td
frontends/tf-frontend/tools/tf_frontend_main.cc

1. add new pattern to replace whereOp to static shape Op
2. add new parttern to rewrite where to reduce boundary of where bounded shape
3. add command line option to choose parrtern 1 or pattern 2

[tf-frontend] replace where to static shape op

---

compiler/README.md
compiler/lib/Dialect/mhlo/CMakeLists.txt

- update Readme with AArch64 platform settings
- fix potential compilation error on AArch64 platform

[compiler] fix compilation on AArch64 platform

---

compiler/include/byteir/Conversion/HloToCat/ConvertHloToCat.h
compiler/include/byteir/Conversion/Passes.h
compiler/include/byteir/Conversion/Passes.td
compiler/include/byteir/Dialect/Cat/IR/CatOps.td
compiler/lib/Conversion/HloToCat/CMakeLists.txt
compiler/lib/Conversion/HloToCat/ConvertHloToCat.cpp
compiler/lib/Dialect/mhlo/Transforms/FuseTransposeIntoDotGeneral.cpp
compiler/python/byteir/compile.py
compiler/python/byteir/dialects/cat/ir_processor.py
compiler/python/byteir/dialects/cat/ir_translator/backend/ait_registry.py
compiler/python/byteir/tools/cat_executor.py
compiler/python/test/dialects/cat/ait/numerical/layernorm.mlir
compiler/python/test/dialects/cat/ait/numerical/matmul.mlir
compiler/python/test/dialects/cat/ait/profile/matmul.mlir
tests/numerical_test/execute.py
tests/numerical_test/profiler.py

* support valid-cat-ops in `convert-hlo-to-cat`
* change e2e report to unique_name

[compiler] convert hlo to cat

---

compiler/lib/Pipelines/AffineOpt.cpp
compiler/lib/Pipelines/HloFusionOpt.cpp
compiler/lib/Pipelines/LinalgTensorOpt.cpp
compiler/lib/Pipelines/SCFOpt.cpp
compiler/python/byteir/compile.py
compiler/python/byteir/tools/compiler.py
compiler/scripts/gen_testcases.py
compiler/test/E2E/Host/Case0/00_Input.mlir
compiler/test/E2E/Host/Case0/TotalPipeline.mlir
compiler/test/E2E/Host/Case0_Bytecode/00_Input.mlir
compiler/test/E2E/Host/Case1/00_Input.mlir
compiler/test/E2E/Host/Case1/TotalPipeline.mlir
compiler/test/E2E/Host/RngNormal/00_Input.mlir
compiler/test/E2E/Host/RngNormal/TotalPipeline.mlir
compiler/test/E2E/Host/RngUniform/00_Input.mlir
compiler/test/E2E/Host/RngUniform/TotalPipeline.mlir
compiler/test/E2E/Host/Transpose/00_Input.mlir
compiler/test/E2E/Host/Transpose/TotalPipeline.mlir
compiler/test/E2E/Host/TypeCvt/00_Input.mlir
compiler/test/E2E/Host/TypeCvt/TotalPipeline.mlir

* add `cpu_arch` in `compiler.py`
* align cpp & python's `target`

[compiler] add cpu arch option

---

compiler/include/byteir/Analysis/ShapeAnalysis.h
compiler/include/byteir/Dialect/mhlo/Analysis/ShapeAnalysis.h
compiler/lib/Dialect/mhlo/Analysis/ShapeAnalysis.cpp

fix bug for clang compiliation

[compiler] fix bug for clang compiliation

---

compiler/include/byteir/Conversion/HloToByreTensor/HloToByreTensor.h
compiler/include/byteir/Conversion/Passes.td
compiler/include/byteir/Pipelines/ByreTensorOpt.h
compiler/lib/Conversion/HloToByreTensor/HloToByreTensor.cpp
compiler/lib/Pipelines/ByreTensorOpt.cpp
compiler/python/byteir/compile.py
compiler/python/byteir/dialects/cat/ir_processor.py
compiler/python/byteir/dialects/cat/ir_translator/ait_builder.py
compiler/python/byteir/tools/compiler.py
compiler/test/Conversion/HloToByreTensor/compute_ops.mlir

[compiler] add enable-tf32 option

---

compiler/lib/Pipelines/ByreTensorOpt.cpp
frontends/torch-frontend/torch-frontend/python/torch_frontend/byteir_backend/config.py
frontends/torch-frontend/torch-frontend/python/torch_frontend/byteir_backend/inner_compile.py

[dynamo] support enable_tf32 in byteir_backend

---

frontends/tf-frontend/tf_mlir_ext/pipelines/customized_tf_to_mhlo.cc

infer shape after convert where to static shape op

[tf-frontend] infer shape after convert where to static shape op

---

frontends/torch-frontend/scripts/envsetup.sh
frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToCustomCall.cpp
frontends/torch-frontend/torch-frontend/python/test/test_torchscript/test_byteir_customcall_ops.py
frontends/torch-frontend/torch-frontend/python/test/test_torchscript/test_ops.py
frontends/torch-frontend/torch-frontend/python/torch_frontend/compile.py
frontends/torch-frontend/torch-frontend/test/Conversion/ConvertTorchToCustomCall.mlir

* unify `argmax` to `max.dim`
* support `argmin` and `min.dim`

[torch-frontend] update torch-mlir and support argmin

---

tests/numerical_test/gen_brt_tests.py

[e2e] use np.savez and rename to gen_brt_tests

---

frontends/torch-frontend/torch-frontend/include/torch-frontend/Conversion/ConvertTorchToCustomCall.h
frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToCustomCall.cpp
frontends/torch-frontend/torch-frontend/python/torch_frontend/__init__.py
frontends/torch-frontend/torch-frontend/python/torch_frontend/compile.py
frontends/torch-frontend/torch-frontend/test/Conversion/ConvertTorchToCustomCall.mlir

so that it could avoid to decompose mat ops.

[torch-frontend] support convert math ops to custom call

---

.gitignore
compiler/doc/byteir_hlo_custom_call.md

* add example for coarse-grained op

[doc] update custom call doc

---

frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToCustomCall.cpp
frontends/torch-frontend/torch-frontend/python/torch_frontend/compile.py
frontends/torch-frontend/torch-frontend/test/Conversion/ConvertTorchToCustomCall.mlir

* remove `torch.` prefix
* add `verbose` option in `torch.compile`

[torch-frontend] fix lowering math ops to custom call

---

compiler/include/byteir/Transforms/GraphClusteringByDevice.h
compiler/include/byteir/Transforms/Passes.td
compiler/lib/Transforms/GraphClusteringByDevice.cpp
compiler/test/Transforms/testGraphClusteringByDeviceOpNum.mlir
compiler/test/lib/Analysis/CMakeLists.txt
compiler/test/lib/Analysis/TestGraphClusteringByDeviceOpNum.cpp
compiler/tools/byteir-opt/byteir-opt.cpp

[compiler] enable cluster multi device sub-graph for GraphClusteringByDevicePass

---

frontends/tf-frontend/tools/tf_frontend_main.cc

[tf-frontend] print error message for TF_LoadLibrary

---

compiler/lib/Dialect/MemRef/Transforms/RemoveCopy.cpp
compiler/test/Dialect/MemRef/removeCopy.mlir

[compiler] hotfix remove copy with continues slice, while src is a strided view

---

frontends/tf-frontend/tf_mlir_ext/tests/fuse_tf_ops.mlir
frontends/tf-frontend/tf_mlir_ext/transforms/fuse_tf_ops.cc

[tf-frontend] add new pattern to remove tf.ReshapeOp

---

compiler/dialects/include/byteir/Dialect/Ccl/IR/CclOps.td
compiler/dialects/lib/Dialect/Ccl/IR/CclOps.cpp

[feat]: add ccl.reduce/scatter/gather op

---

compiler/lib/Dialect/mhlo/Transforms/GenericFusion.cpp
compiler/lib/Dialect/mhlo/Util/Util.cpp
compiler/scripts/gen_testcases_and_check_diff.sh
compiler/test/Dialect/Mhlo/transforms/elementFusion.mlir
compiler/test/E2E/CUDA/AliasLikeGPU/10b_ptx_codegen.mlir
compiler/test/E2E/CUDA/AliasLikeGPU/2_linalg_tensor_opt.mlir
compiler/test/E2E/CUDA/AliasLikeGPU/3_byre_tensor_opt.mlir
compiler/test/E2E/CUDA/AliasLikeGPU/4_bufferize_opt.mlir
compiler/test/E2E/CUDA/AliasLikeGPU/5_alternative_scf_opt.mlir
compiler/test/E2E/CUDA/AliasLikeGPU/6_gpu_opt.mlir
compiler/test/E2E/CUDA/AliasLikeGPU/7_set_space_opt.mlir
compiler/test/E2E/CUDA/AliasLikeGPU/8_byre_opt.mlir
compiler/test/E2E/CUDA/AliasLikeGPU/9a_byre_host.mlir
compiler/test/E2E/CUDA/AliasLikeGPU/9b_nvvm_codegen.mlir
compiler/test/E2E/CUDA/AliasLikeGPU/device_output.ptx
compiler/test/E2E/CUDA/AliasLikeGPU/host_output.mlir

* support elementwise fusion cross reshape

[compiler] refactor elementwise fusion

---

compiler/include/byteir/Dialect/mhlo/Passes.h
compiler/include/byteir/Dialect/mhlo/Passes.td
compiler/include/byteir/Dialect/mhlo/Transforms/DecomposeMhloCustomCallOps.h
compiler/lib/Dialect/mhlo/CMakeLists.txt
compiler/lib/Dialect/mhlo/Transforms/DecomposeMhloCustomCallOps.cpp
compiler/lib/Pipelines/HloGraphOpt.cpp
compiler/python/byteir/compile.py
compiler/test/Dialect/Mhlo/transforms/DecomposeMhloCustomCallOps.mlir
tests/numerical_test/mlir_tests/cpu_ops/custom_call_byteir_addn.mlir

* decompose `byteir.addn` to `mhlo.add`

[compiler] add decompose-mhlo-custom-call-ops pass

---

compiler/include/byteir/Dialect/mhlo/Passes.td
compiler/lib/Dialect/mhlo/Transforms/DecomposeMhloCustomCallOps.cpp
compiler/lib/Dialect/mhlo/Transforms/PassDetail.h
compiler/test/Dialect/Mhlo/transforms/DecomposeMhloCustomCallOps.mlir
tests/numerical_test/mlir_tests/cpu_ops/custom_call_byteir_arg_max.mlir

[compiler] support decomposition of byteir.arg_max/arg_min

---

compiler/lib/Dialect/mhlo/Transforms/GenericFusion.cpp
compiler/lib/Pipelines/HloGraphOpt.cpp
compiler/test/Dialect/Mhlo/transforms/elementFusion.mlir
compiler/test/Pipelines/LinalgTensorOpt/elementwiseCodegen.mlir

* fuse scalar elementwise op cross broadcast

[compiler] support fuse scalar elementwise into broadcast

---

compiler/include/byteir/Dialect/Byre/ByreOps.td
compiler/lib/Conversion/MemrefToByre/MemrefToByre.cpp
compiler/lib/Dialect/Byre/IR/ByreDialect.cpp
compiler/test/Conversion/MemrefToByre/memref_to_byre.mlir
compiler/test/Conversion/ToByre/convertMemRefToByre.mlir

* fix memref.copy to byre.copy
* implement eliminate identity byre.alias as fold

[compiler] enhance byre.alias

---

runtime/include/brt/backends/cuda/device/cuda_work_queue.h
runtime/lib/backends/cpu/providers/default/copy/copy.cc
runtime/lib/backends/cpu/providers/default/copy/copy.h
runtime/lib/backends/cpu/providers/default/cpu_provider.cc
runtime/test/backends/cpu/providers/default/kernel/copy_test.cc
runtime/test/backends/cpu/providers/default/kernel/non_zero_test.cc
runtime/test/backends/cpu/providers/default/kernel/repeat_test.cc
runtime/test/backends/cpu/providers/default/kernel/tf_select_test.cc
runtime/test/backends/cpu/providers/default/kernel/tf_string_to_number_test.cc
runtime/test/backends/cpu/providers/default/kernel/topk_test.cc
runtime/test/backends/cpu/providers/default/kernel/typecvt_test.cc
runtime/test/backends/cuda/providers/default/kernel/copy_test.cc
runtime/test/backends/cuda/providers/default/kernel/elementwise_test.cc
runtime/test/backends/cuda/providers/default/kernel/transpose_test.cc
tests/numerical_test/mlir_tests/cpu_ops/slice_view_like.mlir

[runtime] support cpu2cpu copy

---

frontends/torch-frontend/torch-frontend/lib/Transforms/CanonicalizeExt.cpp

[torch-frontend] fix canonicalize-ext on index type

---

compiler/lib/Dialect/Byre/IR/ByreDialect.cpp
compiler/python/byteir/compile.py
compiler/python/test/api/test_py_api.py

[compiler] check diff after byre serialization

---

.github/workflows/daily_ci.yaml

This updates e2e test path in daily ci

[ci] Update daily_ci.yaml

---

frontends/torch-frontend/examples/inference/brt_backend.py
frontends/torch-frontend/examples/inference/mlp.py

[e2e] add mlp inference e2e example

---

frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToStablehloExt.cpp
frontends/torch-frontend/torch-frontend/test/Conversion/ConvertTorchToStablehloExt.mlir

[torch-frontend] fix pow.Scalar's lowering

---

compiler/lib/CAPI/Translation.cpp
compiler/lib/Dialect/Byre/IR/Serialization/Versioning.cpp

[compiler] use byre serial's parser to parse version

---

compiler/include/byteir/Utils/OpInterfaceUtils.h
compiler/lib/CAPI/Dialects.cpp
compiler/lib/Dialect/Byre/IR/Serialization/Versioning.cpp
compiler/lib/Utils/OpInterfaceUtils.cpp
compiler/tools/byteir-opt/byteir-opt.cpp

[compiler] fix typo

---

compiler/include/byteir/Transforms/ModuleTag.h
compiler/include/byteir/Transforms/Passes.h
compiler/include/byteir/Transforms/Passes.td
compiler/lib/Transforms/CMakeLists.txt
compiler/lib/Transforms/ModuleTag.cpp
compiler/python/byteir/compile.py
compiler/python/test/api/test_py_api.py

[compiler] support byre srialization on cuda

---

compiler/python/CMakeLists.txt
compiler/python/setup.py

[compiler] reduce wheel package size

---

frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToCustomCall.cpp
frontends/torch-frontend/torch-frontend/test/Conversion/ConvertTorchToCustomCall.mlir

[torch-frontend] support negative axis on byteir.l2_norm

---

frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToStablehloExt.cpp
frontends/torch-frontend/torch-frontend/python/test/test_torchscript/test_ops.py

[torch-frontend] fix expand_as with different dtype

---

compiler/include/byteir-c/Translation.h
compiler/include/byteir/Utils/ModuleUtils.h
compiler/lib/CAPI/Translation.cpp
compiler/lib/Utils/ModuleUtils.cpp
compiler/python/ByteIRModules.cpp
compiler/python/test/api/test_py_api.py
compiler/test/Utils/testMergeTwoModulesCase2.mlir
compiler/test/Utils/testMergeTwoModulesCase2_1.mlir

[compiler] support merge two modules with skip_name_check mode

---

frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToCustomCall.cpp
frontends/torch-frontend/torch-frontend/python/test/test_torchscript/test_byteir_customcall_ops.py

[torch-frontend] support lowering aten.bilinear with half_pixel mode

---

frontends/onnx-frontend/README.md
frontends/onnx-frontend/requirements.txt

This PR updates the build instructions for onnx-frontend.

[onnx-frontend] Update onnx-frontend Readme

---

compiler/lib/Dialect/mhlo/Transforms/DecomposeMhloCustomCallOps.cpp
compiler/test/Dialect/Mhlo/transforms/DecomposeMhloCustomCallOps.mlir
tests/numerical_test/mlir_tests/cpu_ops/custom_call_byteir_arg_max_i32.mlir
tests/numerical_test/mlir_tests/cpu_ops/custom_call_byteir_arg_min.mlir
tests/numerical_test/mlir_tests/cpu_ops/custom_call_byteir_arg_min_i32.mlir

[compiler] support cpu codegen of byteir.arg_max with integer type

---

frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToCustomCall.cpp
frontends/torch-frontend/torch-frontend/python/torch_frontend/flash_attn_op.py
frontends/torch-frontend/torch-frontend/test/Conversion/ConvertTorchToCustomCall.mlir

[torch-frontend] support lowering triton.xxx to stablehlo.custom_call

---

frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToCustomCall.cpp
frontends/torch-frontend/torch-frontend/python/test/test_torchscript/test_byteir_customcall_ops.py
frontends/torch-frontend/torch-frontend/test/Conversion/ConvertTorchToCustomCall.mlir

[torch-frontend] lowering aten.upsample_nearest2d to byteir.resize

---

compiler/include/byteir/Transforms/GraphClusteringByDevice.h
compiler/lib/Transforms/GraphClusteringByDevice.cpp
compiler/test/lib/Analysis/TestGraphClusteringByDeviceOpNum.cpp

[compiler] add validateGraphFn option to GraphClusteringByDevicePass

---

frontends/torch-frontend/torch-frontend/python/test/test_torchscript/test_ops.py

[torch-frontend] update torch-mlir to support nll_loss_forward

---

frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToCustomCall.cpp
frontends/torch-frontend/torch-frontend/python/test/test_fximporter/test_custom_ops.py
frontends/torch-frontend/torch-frontend/python/test/test_math_custom_ops.py

[torch-frontend] fix math custom op's lowering

---

compiler/include/byteir/Dialect/mhlo/DynamicShapeOpRegister/Register.h
compiler/lib/Dialect/mhlo/DynamicShapeOpRegister/StridedSlice.cpp
compiler/test/Transforms/shapeReification.mlir
compiler/test/Transforms/staticShapeInference.mlir
frontends/tf-frontend/tf_mlir_ext/tests/set_repeat_out_batch_size.mlir
frontends/tf-frontend/tf_mlir_ext/transforms/set_repeat_out_batch_size.cc

[tf-frontend] fix bug of setting repeat output batch_size
[compiler] add shape reification function for StridedSlice

[compiler] add shape reification function for StridedSlice

---

frontends/torch-frontend/torch-frontend/lib/Conversion/ConvertTorchToCustomCall.cpp
frontends/torch-frontend/torch-frontend/python/test/test_torchscript/test_byteir_customcall_ops.py
frontends/torch-frontend/torch-frontend/python/torch_frontend/compile.py
frontends/torch-frontend/torch-frontend/test/Conversion/ConvertTorchToCustomCall.mlir

[torch-frontend] lowering aten.sort to byteir.top_k

---

frontends/torch-frontend/torch-frontend/python/CMakeLists.txt
frontends/torch-frontend/torch-frontend/python/test/test_utils/test_jit_transforms.py
frontends/torch-frontend/torch-frontend/python/torch_frontend/__init__.py
frontends/torch-frontend/torch-frontend/python/torch_frontend/tools/compiler.py
frontends/torch-frontend/torch-frontend/python/torch_frontend/utils/__init__.py
frontends/torch-frontend/torch-frontend/python/torch_frontend/utils/jit_transforms.py

rewrite fill_ or copy_ to slice_scatter.

[torch-frontend] add jit transforms

---

frontends/torch-frontend/build-requirements.txt
frontends/torch-frontend/torch-frontend/python/CMakeLists.txt
frontends/torch-frontend/torch-frontend/python/setup.py

[torch-frontend] fix setup.py's build_dir

---

frontends/tf-frontend/tf_mlir_ext/tests/mhlo_legalize_tf_ext.mlir
frontends/tf-frontend/tf_mlir_ext/transforms/mhlo_legalize_tf_ext.cc

1. convert tf.BatchMatMulV2 to mhlo.dot_general
2. convert tf.StridedSlice to mhlo.slice/mhlo.dynamic_slice/mhlo.real_dynamic_slice

[tf-frontend] fix tf.BatchMatmul and tf.StridedSlice conversion pattern

---

frontends/tf-frontend/tf_mlir_ext/tests/mhlo_legalize_tf_ext.mlir
frontends/tf-frontend/tf_mlir_ext/transforms/mhlo_legalize_tf_ext.cc

fix the value of end for tf.StridedSlice, when the shrink mask takes effect and begin = -1

[tf-frontend] fix tf.StridedSlice

---

compiler/include/byteir/Dialect/Shape/Passes.td
compiler/include/byteir/Dialect/Shape/Transforms/InsertInputShapeConstraint.h
compiler/lib/Dialect/Shape/CMakeLists.txt
compiler/lib/Dialect/Shape/Transforms/InsertInputShapeConstraint.cpp
compiler/lib/Dialect/Shape/Transforms/PassDetail.h
compiler/test/Dialect/Shape/insertInputShapeConstraint.mlir

* add `all-dynamic-batch-same` mode

[compiler] add insert-input-shape-constraint pass
